### ISSUE TITLE
Line Tax Version: When Preferences is set to 1.000,00 VAT is not calculated correctly

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#2]
The following issue exists both in AR and AP modules.

When 'Preferences--Number Format' is set to 1.000,00 VAT is not calculated correctly on "Update":

![bildschirmfoto 2015-08-27 um 17 08 49](https://cloud.githubusercontent.com/assets/100664/9524307/897dd21e-4cde-11e5-8b3d-9334143d5760.png)

And if "Tax included" checkbox is market numbers become strange:

![bildschirmfoto 2015-08-27 um 17 07 25](https://cloud.githubusercontent.com/assets/100664/9524317/97898c18-4cde-11e5-9513-4c7d5d17afb9.png)

**Comment by ledger123** [comment]
This is also fixed with the lastest push. Kindly test.
Regards

**Comment by sweitmann** [comment]
Thanks, Armaghan. Tested. And as discussed on the phone, if you try entering the same "Amount" (102) and "Tax" (8%) as in my example above and you will see this issue is not quite solved yet.

**Comment by ledger123** [comment]
Hi Sebastian,

This is fixed and pushed. Please test to see if everything is ok.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Wonderful! Works perfect now. Thanks. Closing this ticket now.

Regards
Sebastian
