### ISSUE TITLE
** fxamount and fxpaid

### ISSUE THREAD

**Issue by sweitmann** [ledger123/runmyaccounts#36]
In the ap and ar tables the foreign currency totals are saved in fxamount and fxpaid.  

![006](https://cloud.githubusercontent.com/assets/100664/11913536/56a226be-a667-11e5-8ccf-a93d0b022ab4.png)

The problem is that the foreign currency totals are only recorded in fxamount and fxpaid when you use 'AR--Sales Invoice'. 

When you use 'AR--Add Transaction', 'AR-Credit Note' or 'AR--Credit Invoice' instead nothing is recorded in fxamount and fxpaid. The same applies to all the AP transactions.

It would be great if fxamount and fxpaid could be filled with the foreign currency totals consequently for all AR and AP transactions. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been fixed.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. Works fine for all AR and AP transactions, except for 

AP--Vendor Invoice
and 
AP-Debit Invoice

These two AP transactions still leave the fxamount and fxpaid empty. 

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

This has been done and code pushed to develop1.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested. Solved; you have done it again! Thanks for all your help. Closing this ticket now.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Nils showed me that this issue is not quite solved yet. Let's talk about in during my visit.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

I was able to reproduce this now: fxamount and fxpaid are not recorded/updated when you skip clicking the "update" button.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have fixed this and pushed code. 

Regards

**Comment by sweitmann** [comment]
Hi Armghan, 

I've done some more testing (branch develop2) and I'm afraid it seems that this issue is not solved yet.

a.) First I create an AR transaction, update and post:

![001](https://cloud.githubusercontent.com/assets/100664/14006282/266b863e-f16c-11e5-911a-25933a619284.png)

b.) So far, so good:

![001b](https://cloud.githubusercontent.com/assets/100664/14006287/335475ae-f16c-11e5-9094-4637b680b4bb.png)

c.) Then I open the same transaction, change the numbers and post (without updating):

![001c](https://cloud.githubusercontent.com/assets/100664/14006301/578fc978-f16c-11e5-95c6-a63038ba1fb2.png)

d.) And this time fxamount and fxpaid are not updated:

![001d](https://cloud.githubusercontent.com/assets/100664/14006311/6f0eb0b4-f16c-11e5-90c8-6f457ca1c366.png)

The same thing happens when I run the same test on AP.

Regards,
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

The new update I just pushed should take care of it. I am now running update from within post so I shall request to do bit more testing in case this messes up anything else on this screen.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Thanks. It seems to work fine for AR and AP transactions now. But the issue also seems to remain with the Sales Invoice and Vendor Invoice. 

Here an example.

a.) I enter the amounts in a Sales Invoice and post (without updating):

![001](https://cloud.githubusercontent.com/assets/100664/14018441/1c02d172-f1ce-11e5-9916-e35fd9160779.png)

b.) In the database it then only inserts the fxamount, but not the fxpaid:

![001b](https://cloud.githubusercontent.com/assets/100664/14018465/384afff8-f1ce-11e5-9acb-5855bf5300d0.png)

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

I have pushed another update. Hopefully this should fix this issue permanently.

Regards

**Comment by ledger123** [comment]
Hi Sebastian,

Now I have moved all updates related to this function to 036_fxamount_fxpaid branch. I created this new branch off latest master so that it can be quickly merged by Nils.

Have a look and confirm.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

When I try to post a sales invoice, I get an "Internal Server Error".

![bildschirmfoto vom 2016-04-25 17 17 31](https://cloud.githubusercontent.com/assets/100664/14788734/9ebc2376-0b09-11e6-96a8-168e9bf41e4c.png)

Any ideas?

Regards

**Comment by ledger123** [comment]
Hi Sebastian, 

Today I have updated this ticket again and reverted old / incorrect code.
Have a look and let me know if it works ok or not.

Regards

**Comment by sweitmann** [comment]
Hi Armaghan, 

Thanks, yes, the "Internal Server Error" is gone now, but the other issue (see my comment above from 24 Mar) remains.  

Regards

**Comment by ledger123** [comment]
Hi Sebastian,
I have posted fix which which correctly updates fxamount,fxpaid  even without Update button.
Regards

**Comment by sweitmann** [comment]
Hi Armaghan,

Tested and it works beautifully for 'AR--Add Transaction', 'AR--Sales Invoice' and 'AP--Add Transaction'. 

Only two small issues remain: 

1.) If I try to login whilst on the "036_fxamount_fxpaid" branch I get the error message:
![bildschirmfoto 2016-06-15 um 18 32 48](https://cloud.githubusercontent.com/assets/100664/16088475/9ac94f8c-3327-11e6-8387-a82c8bcdeb74.png)

In order to test it I had to login whilst on the "master" branch and switch to the "036_fxamount_fxpaid" branch after having logged in. So, there seems to be some kind of problem during login here.

2.) When using 'AP--Vendor Invoice' the fxpaid amount is not registered in the database:
![bildschirmfoto 2016-06-15 um 18 29 11](https://cloud.githubusercontent.com/assets/100664/16088388/2a3f932a-3327-11e6-827a-8769af23d8a5.png)

Regards
Sebastian

**Comment by ledger123** [comment]
Hi Sebastian,

1. This error is actually 'Dataset is newer than sql-ledger version' which is caused by version mismatch. Actual error is shown only in apache log due to recent security changes.

You can fix this with UPDATE defaults SET fldvalue='2.8.10' where fldvalue='2.8.11';

2. AP--Vendor invoice is fixed now and code pushed.

Regards

**Comment by sweitmann** [comment]
Wonderful, thanks Armaghan! Closing this ticket now.
